### ISSUE TITLE
Speicherfunktion

### ISSUE THREAD

**Issue by axiades** [Albritter/Vmail#1]
Hallo,

Ich wollte mal fragen ob du eine Speicherfunktion einbauen könntest dass man mehrere Server Einspeichern Kann und dann entsprechend die daten nur einmal eingeben muss.

LG

PS: Wies genutzt wird hab ich rausgefunden is ja Java 🗡

**Comment by Halbritter** [comment]
Wenn Java installiert ist sollte sich das Programm mit einem Doppelklick starten lassen.
Um sich mit dem Mailserver zu verbinden wird ein MySQL Benutzer mit Schreibrechten benötigt.
Auch muss sich der Benutzer von Extern an die Datenbank anmelden können. 

Ich werde diesbezüglich morgen die Readme ergänzen. 

Am 18. Februar 2018 20:56:41 MEZ schrieb Phillip Lurgenstein <notifications@github.com>:
>Hallo,
>
>Ich wollte mal fragen wie ich dass ganze nutzen soll?
>
>Leider Steht davon nichts in der Readme ...
>
>LG
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Halbritter/MailAdmin/issues/1

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Halbritter** [comment]
Einspeichern im sinne von, dass es für "Server" ein drop down Menü mit den letzen erolgreichen Logins gibt? Wenn man dann auf eine Eintrag klickt werden Datenbank Name und Benutzer eingefügt.
So würde ich mir das zumindest vorstellen. 
Ich werde morgen mal schauen.

**Comment by Halbritter** [comment]
Funktion eingbaut. 
Siehe commit 6e64db85d98e39b21a06d93bc7d8c35a59db3a27
Sie wird in 1.5 zur verfügung stehen. (Schon online)
