### ISSUE TITLE
MailAdmin Installation

### ISSUE THREAD

**Issue by werner53844** [Albritter/Vmail#3]
Hallo,
wie kann ich MailAdmin 1.5 installieren?
Gruß

**Comment by Halbritter** [comment]
Moin, 

Du brauchst java (1.8 oder höher) auf deinem Client 
Danach musst du dafür sorgenndas du dich von deinem Rechner aus an der Datenbank anmelden kannst. Standardmäßig ist MySQL/MariaDB aufnlocalhost beschränkt. 

Wenn du bei diesem Schritt Hilfe brauchst brauche ich deine MySQL oder Maridb Version.

Danach musst du einen Datenbank Benutzer anlegen der im der vmail Datenbank lesen und schreiben darf. Der muss sich von deinem Rechner aus anmelden dürfen ***@***.*** z.b. würde als user nicht ohne weiteres funktionieren)
Wenn du ein gutes Kennwort verwendest sollte z.b. mailadmin@% in Ordnung sein. Mit dem Benutzer kannst du dich jetzt in mailadmin anmelden. 

Die jar Datei musst du mit Java starten (rechtsklick öffnen mit)

Das Tool ist schon älter daher ist die Doku leider recht mies. Viel8cht komme ich ja nochmal dazu sie anzupassen


Am 8. Juni 2022 21:03:12 MESZ schrieb werner53844 ***@***.***>:
>Hallo,
>
>wie kann ich MailAdmin 1.5 installieren?
>
>Gruß
>
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/Halbritter/MailAdmin/issues/3
>
>You are receiving this because you are subscribed to this thread.
>
>
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Halbritter** [comment]
Hallo,

Brauchst du noch weitere unterstützung?
